# Generated by Django 5.1.15 on 2026-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geocode_confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='fuel_optimi_state_9c8f0e_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_optimi_latitud_cbced2_idx')],
                'constraints': [models.UniqueConstraint(fields=('opis_id', 'address'), name='unique_station_opis_address')],
            },
        ),
    ]
